models:
  sqlcoder:
    type: llamacpp
    model_path: /home/pablo/models/llama-3-sqlcoder-8b.Q4_K_M.gguf
    context_length: 4096
    n_gpu_layers: 0
    n_threads: 8
    temperature: 0.1
    top_p: 0.95

  mistral:
    type: llamacpp
    model_path: /home/pablo/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
    context_length: 4096
    n_gpu_layers: 35
    n_threads: 8
    temperature: 0.1
    top_p: 0.5

    