models:
  sqlcoder:
    type: llamacpp
    model_path: /home/pablo/models/sqlcoder-7b/sqlcoder-7b-q5_k_m.gguf
    context_length: 4096
    n_gpu_layers: 0
    n_threads: 8
    temperature: 0.1
    top_p: 0.95

  mistral:
    type: llamacpp
    model_path: /home/pablo/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
    context_length: 8192
    n_gpu_layers: 35
    n_threads: 8
    temperature: 0.7
    top_p: 0.9

